export {
  createCompositeEnergyModel,
  createLinearExternalForceTerm,
  createQuadraticTargetTerm,
  type CompositeEnergyEvaluation,
  type CompositeEnergyModel,
  type DenseEnergyEvaluation,
  type DifferentiableEnergyModel,
  type DifferentiableEnergyTerm,
  type EnergyContribution,
  type EnergyTermKind,
  type LinearExternalForceOptions,
  type QuadraticTargetOptions,
} from "./energy";
export {
  buildLowFrequencyTrainingPoses,
  selectCubatureSamples,
  type CubatureSelection,
} from "./cubature";
export {
  assembleRestLinearSystem,
  computeLinearTetrahedronStiffness,
  computeLumpedMasses,
  computeRestTetraData,
  type TetrahedronStiffnessResult,
} from "./fem";
export {
  centralDifferenceGradient,
  centralDifferenceHessian,
  relativeError,
  type ScalarFunction,
  type VectorFunction,
} from "./finite-difference";
export {
  choleskyFactor,
  determinant3,
  dot,
  invert3,
  multiply3,
  solveCholesky,
  solveDenseLinearSystem,
  squaredNorm,
} from "./math";
export {
  appendTetrahedralMeshes,
  extractBoundarySurface,
  generateRegularCuboidMesh,
  getTetrahedronCount,
  getVertexCount,
  transformTetrahedralMesh,
  validateTetrahedralMesh,
} from "./mesh";
export {
  buildPrecomputedScene,
  computeExactVertexBasis,
  exactBasisToActiveMatrix,
} from "./precompute";
export {
  activeCoordinatesFromFullPositions,
  computeCorotatedLinearRotations,
  computeDirectComplementaryEquilibriumBasis,
  createCorotatedLinearImplicitEulerOracle,
  evaluateCorotatedLinearTetrahedron,
  fullPositionsFromActiveCoordinates,
  polarRotation3,
  solveEquilibriumBasisNewtonStep,
  solveFullNewtonStep,
  type ComplementaryEquilibriumBasis,
  type CorotatedLinearElementEvaluation,
  type CorotatedLinearImplicitEulerOptions,
  type CorotatedLinearImplicitEulerOracle,
  type EnergyEvaluation,
  type ImplicitEulerEnergyComponents,
  type ImplicitEulerEvaluation,
  type QuadraticFloorContact,
} from "./oracle";
export {
  PHASE0_ORACLE_CORPUS_CASE_COUNT,
  PHASE0_ORACLE_CORPUS_GENERATOR_VERSION,
  PHASE0_ORACLE_CORPUS_ID,
  PHASE0_ORACLE_CORPUS_SEED,
  PHASE0_ORACLE_DISPLACEMENT_SCALE,
  PHASE0_ORACLE_FIXTURE_ID,
  PHASE0_ORACLE_MINIMUM_DETERMINANT,
  PHASE0_ORACLE_REST_POSITIONS,
  PHASE0_ORACLE_TIMESTEP,
  PHASE0_REFERENCE_MATERIAL,
  buildPhase0OracleDefinition,
  buildPhase0OracleFixture,
  evaluatePhase0OraclePose,
  generatePhase0OraclePoseCorpus,
  measurePhase0OraclePoseErrors,
  type Phase0OracleFixture,
  type Phase0OraclePose,
  type Phase0OraclePoseErrors,
  type Phase0OraclePoseEvaluation,
  type Phase0OraclePoseKind,
} from "./phase0-canonical";
export type {
  ColorRgba,
  CubatureSample,
  LinearMaterial,
  MeshTransform,
  PrecomputedScene,
  PrecomputeOptions,
  RegularCuboidOptions,
  RestLinearSystem,
  RestTetraData,
  SceneCamera,
  SceneDefinition,
  SceneLandmark,
  SimulationSettings,
  SurfaceTopology,
  TetrahedralMesh,
  Vec3,
  VertexPrecomputation,
} from "./types";
