export {
  createCompositeEnergyModel,
  createLinearExternalForceTerm,
  createQuadraticTargetTerm,
  type CompositeEnergyEvaluation,
  type CompositeEnergyModel,
  type DenseEnergyEvaluation,
  type DifferentiableEnergyModel,
  type DifferentiableEnergyTerm,
  type EnergyContribution,
  type EnergyTermKind,
  type LinearExternalForceOptions,
  type QuadraticTargetOptions,
} from "./energy";
export {
  buildLowFrequencyTrainingPoses,
  fitNonnegativeColumnWeights,
  selectGreedyNonnegativeColumns,
  selectCubatureSamples,
  type CubatureSelection,
  type GreedyNonnegativeColumnSelection,
  type GreedyNonnegativeColumnSelectionOptions,
  type NonnegativeColumnFit,
} from "./cubature";
export {
  assembleRestLinearSystem,
  computeLinearTetrahedronStiffness,
  computeLumpedMasses,
  computeRestTetraData,
  computeTetrahedronShapeGradients,
  type TetrahedronStiffnessResult,
} from "./fem";
export {
  centralDifferenceGradient,
  centralDifferenceHessian,
  relativeError,
  type ScalarFunction,
  type VectorFunction,
} from "./finite-difference";
export {
  buildVertexDeformationGradientStencil,
  computeVertexPolarFrames,
  evaluateVertexDeformationGradients,
  type VertexDeformationGradientStencil,
} from "./deformation-gradient";
export {
  choleskyFactor,
  determinant3,
  dot,
  invert3,
  multiply3,
  solveCholesky,
  solveDenseLinearSystem,
  squaredNorm,
} from "./math";
export {
  appendTetrahedralMeshes,
  extractBoundarySurface,
  generateRegularCuboidMesh,
  getTetrahedronCount,
  getVertexCount,
  transformTetrahedralMesh,
  validateTetrahedralMesh,
} from "./mesh";
export {
  buildPrecomputedScene,
  computeExactVertexBasis,
  exactBasisToActiveMatrix,
} from "./precompute";
export {
  activeCoordinatesFromFullPositions,
  computeCorotatedLinearRotations,
  computeDirectComplementaryEquilibriumBasis,
  createCorotatedLinearImplicitEulerOracle,
  evaluateCorotatedLinearTetrahedron,
  fullPositionsFromActiveCoordinates,
  polarRotation3,
  solveEquilibriumBasisNewtonStep,
  solveFullNewtonStep,
  type ComplementaryEquilibriumBasis,
  type CorotatedLinearElementEvaluation,
  type CorotatedLinearImplicitEulerOptions,
  type CorotatedLinearImplicitEulerOracle,
  type EnergyEvaluation,
  type ImplicitEulerEnergyComponents,
  type ImplicitEulerEvaluation,
  type QuadraticFloorContact,
} from "./oracle";
export {
  createStableNeoHookeanImplicitEulerOracle,
  type NonlinearQuadraticCoordinateTarget,
  type QuadraticTargetEnergy,
  type StableNeoHookeanImplicitEulerComponents,
  type StableNeoHookeanImplicitEulerEvaluation,
  type StableNeoHookeanImplicitEulerGradientComponents,
  type StableNeoHookeanImplicitEulerOptions,
  type StableNeoHookeanImplicitEulerOracle,
} from "./nonlinear-oracle";
export {
  createSelectedCubatureRestrictedLocalModel,
  globalizeSelectedCubatureRestrictedLocal,
  type SelectedCubatureRestrictedGlobalizationResult,
  type SelectedCubatureRestrictedLocalModel,
  type SelectedCubatureRestrictedLocalOptions,
} from "./nonlinear-restricted-energy";
export {
  JGS2_RUNTIME_MAXIMUM_CONVERGENCE_TOLERANCE,
  JGS2_TINY_REFERENCE_RESIDUAL_TOLERANCE,
  acceptOrRevertFeasibleJacobiIteration,
  evaluateJGS2Convergence,
  type JGS2ConvergenceGradientComponents,
  type JGS2ConvergenceOptions,
  type JGS2ConvergenceResult,
  type JGS2JacobiEnergyPair,
  type JGS2JacobiFeasibilityResult,
} from "./nonlinear-iteration";
export {
  JGS2_LOCAL_ARMIJO_C1,
  JGS2_LOCAL_BACKTRACK_FACTOR,
  JGS2_LOCAL_MAX_BACKTRACKS,
  JGS2_LOCAL_MAX_NORMALIZED_SHIFT,
  JGS2_LOCAL_RELATIVE_EIGENVALUE_FLOOR,
  PHASE1_ACCEPTED_DETERMINANT_FLOOR,
  computeJGS2LocalDescentDirection,
  globalizeExactStableNeoHookeanJGS2Local,
  lineSearchRestrictedJGS2LocalDirection,
  minimumSymmetricEigenvalue3,
  type JGS2LocalDirectionResult,
  type JGS2LocalDirectionStatus,
  type JGS2LocalPositiveDefiniteOptions,
  type ExactJGS2LocalGlobalizationOptions,
  type ExactJGS2LocalGlobalizationResult,
  type JGS2RestrictedLocalLineSearchOptions,
  type JGS2RestrictedLocalLineSearchResult,
  type JGS2RestrictedLocalLineSearchStatus,
} from "./nonlinear-globalization";
export {
  createExactStableNeoHookeanJGS2LocalModel,
  evaluateExactStableNeoHookeanJGS2Local,
  projectDenseJGS2LocalTerm,
  type ExactStableNeoHookeanJGS2LocalEvaluation,
  type ExactStableNeoHookeanJGS2LocalModel,
  type ExactStableNeoHookeanJGS2LocalOptions,
  type JGS2LocalProjection,
} from "./jgs2-local";
export {
  NONLINEAR_CUBATURE_CORPUS_VERSION,
  NONLINEAR_CUBATURE_DIRECTION_NORMALIZATION,
  NONLINEAR_CUBATURE_INVERSE_ITERATIONS,
  NONLINEAR_CUBATURE_MINIMUM_POSE_DETERMINANT,
  NONLINEAR_CUBATURE_MODE_COUNT,
  NONLINEAR_CUBATURE_MIXTURE_COEFFICIENT_FORMULA,
  NONLINEAR_CUBATURE_VALIDATION_ONLY_MODE_COUNT,
  NONLINEAR_CUBATURE_VALIDATION_ROTATIONS,
  NONLINEAR_CUBATURE_ROTATED_VALIDATION_COUNT,
  NONLINEAR_CUBATURE_TRAINING_AMPLITUDE,
  NONLINEAR_CUBATURE_VALIDATION_HIGH_AMPLITUDE,
  NONLINEAR_CUBATURE_VALIDATION_HIGH_AMPLITUDE_START,
  NONLINEAR_CUBATURE_VALIDATION_LOW_AMPLITUDE,
  NONLINEAR_CUBATURE_VALIDATION_MIXTURE_COUNT,
  NONLINEAR_CUBATURE_VALIDATION_PREDICTED_BLEND,
  buildNonlinearCubaturePoseCorpus,
  type NonlinearCubaturePose,
  type NonlinearCubaturePoseCorpus,
  type NonlinearCubaturePoseCorpusOptions,
  type NonlinearCubaturePoseKind,
} from "./nonlinear-cubature";
export {
  NONLINEAR_CUBATURE_COLUMN_RANK_RELATIVE_TOLERANCE,
  NONLINEAR_CUBATURE_CO_ROTATION,
  NONLINEAR_CUBATURE_GPU_PARITY_ITERATIONS,
  NONLINEAR_CUBATURE_GPU_UPDATE_TOLERANCE,
  NONLINEAR_CUBATURE_RESIDUAL_METRIC,
  NONLINEAR_CUBATURE_SELECTION_METHOD,
  NONLINEAR_CUBATURE_TARGET_NORMALIZATION,
  NONLINEAR_CUBATURE_TRAINING_RESIDUAL_TOLERANCE,
  NONLINEAR_CUBATURE_UPDATE_RMS_METRIC,
  NONLINEAR_CUBATURE_UPDATE_RMS_TOLERANCE,
  NONLINEAR_CUBATURE_VERTEX_FRAME,
  assembleStableNeoHookeanJGS2LocalSystem,
  buildCurrentCoRotatedCubatureBasisBlocks,
  buildCurrentCoRotatedEquilibriumBasis,
  currentEquilibriumBasisToActiveMatrix,
  evaluateStableNeoHookeanCubatureCandidate,
  selectStableNeoHookeanCubatureSamples,
  type NonlinearCubatureCandidateEvaluation,
  type StableNeoHookeanCubatureContext,
  type StableNeoHookeanCubatureSelection,
  type StableNeoHookeanJGS2LocalSystem,
} from "./nonlinear-cubature-training";
export {
  PHASE0_ORACLE_CORPUS_CASE_COUNT,
  PHASE0_ORACLE_CORPUS_GENERATOR_VERSION,
  PHASE0_ORACLE_CORPUS_ID,
  PHASE0_ORACLE_CORPUS_SEED,
  PHASE0_ORACLE_DISPLACEMENT_SCALE,
  PHASE0_ORACLE_FIXTURE_ID,
  PHASE0_ORACLE_MINIMUM_DETERMINANT,
  PHASE0_ORACLE_REST_POSITIONS,
  PHASE0_ORACLE_TIMESTEP,
  PHASE0_REFERENCE_MATERIAL,
  buildPhase0OracleDefinition,
  buildPhase0OracleFixture,
  evaluatePhase0OraclePose,
  generatePhase0OraclePoseCorpus,
  measurePhase0OraclePoseErrors,
  type Phase0OracleFixture,
  type Phase0OraclePose,
  type Phase0OraclePoseErrors,
  type Phase0OraclePoseEvaluation,
  type Phase0OraclePoseKind,
} from "./phase0-canonical";
export {
  applyStableNeoHookeanTangent,
  assertStableNeoHookeanFeasible,
  cofactor3,
  computeStableNeoHookeanParameters,
  createStableNeoHookeanMaterialTerm,
  directionalCofactor3,
  evaluateStableNeoHookeanDensity,
  evaluateStableNeoHookeanMesh,
  evaluateStableNeoHookeanTetrahedron,
  minimumTetrahedralDeformationDeterminant,
  tetrahedralDeformationDeterminant,
  type StableNeoHookeanDensityEvaluation,
  type StableNeoHookeanMaterialTermOptions,
  type StableNeoHookeanMeshEvaluation,
  type StableNeoHookeanParameters,
  type StableNeoHookeanTetrahedronEvaluation,
} from "./stable-neo-hookean";
export type {
  ColorRgba,
  CubatureSample,
  ElasticMaterialModel,
  LinearMaterial,
  MeshTransform,
  PrecomputedScene,
  PrecomputeOptions,
  RegularCuboidOptions,
  RestLinearSystem,
  RestTetraData,
  SceneCamera,
  SceneDefinition,
  SceneLandmark,
  SimulationSettings,
  SurfaceTopology,
  TetrahedralMesh,
  Vec3,
  VertexPrecomputation,
} from "./types";
